/**
 * Market database seed — AHJ/jurisdiction data for top US commercial construction markets.
 * Run with: npx tsx scripts/seed-markets.ts
 *
 * Sources: municipal websites, permit portals, industry reports (2024–2025)
 * Review times are averages for standard commercial projects; complex/major projects differ.
 */
import { loadEnvConfig } from '@next/env';
import path from 'path';
loadEnvConfig(path.resolve(__dirname, '..'));

import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import * as schema from '../src/lib/db/schema';

const DB_URL = process.env.DATABASE_URL;
if (!DB_URL) throw new Error('DATABASE_URL not set');

const client = postgres(DB_URL);
const db = drizzle(client, { schema });

type JurisdictionSeed = typeof schema.jurisdictions.$inferInsert;

const markets: JurisdictionSeed[] = [
  // ─────────────────────────────────────────────
  // HOUSTON METRO, TX — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Houston Metro',
    city: 'Houston',
    county: 'Harris County',
    state: 'TX',
    ahjName: 'City of Houston Development Services Department',
    portalUrl: 'https://edps.houstontx.gov',
    feeScheduleUrl: 'https://www.houstontx.gov/planning/DevelopRegs/docs_pdfs/feeschedule.pdf',
    phone: '(832) 394-8849',
    email: 'permit@houstontx.gov',
    address: '1002 Washington Ave, Houston, TX 77002',
    avgReviewDaysBuilding: 20,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 25,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['commercial', 'healthcare', 'industrial', 'retail']),
    permitVolume: '~70,000 commercial permits/year',
    yoyGrowthPct: '8.2',
    notes: 'Submit via eDPS portal. Fire permits reviewed by Houston Fire Department separately. TAS (Texas Accessibility Standards) review required for most commercial projects. No zoning code — deed restrictions govern land use.',
  },
  {
    metro: 'Houston Metro',
    city: 'Harris County (unincorporated)',
    county: 'Harris County',
    state: 'TX',
    ahjName: 'Harris County Permits & Infrastructure Dept (HCPID)',
    portalUrl: 'https://permits.harriscountytx.gov',
    feeScheduleUrl: 'https://www.hcpid.org/169/Fee-Schedule',
    phone: '(713) 274-3900',
    address: '1111 Fannin St, Houston, TX 77002',
    avgReviewDaysBuilding: 25,
    avgReviewDaysElectrical: 10,
    avgReviewDaysPlumbing: 10,
    avgReviewDaysMechanical: 12,
    avgReviewDaysFire: null,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['industrial', 'commercial', 'multifamily', 'logistics']),
    permitVolume: '~25,000 commercial permits/year',
    yoyGrowthPct: '6.5',
    notes: 'Covers unincorporated Harris County. HCFCD (Harris County Flood Control) review required if near floodway. No fire department — use Harris County Fire Marshal for fire system permits. Septic/OSSF approval needed without public sewer.',
  },
  {
    metro: 'Houston Metro',
    city: 'Pearland',
    county: 'Brazoria County',
    state: 'TX',
    ahjName: 'City of Pearland Community Development Department',
    portalUrl: 'https://www.pearlandtx.gov/departments/community-development/permits',
    phone: '(281) 652-1600',
    avgReviewDaysBuilding: 15,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 15,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['retail', 'healthcare', 'multifamily']),
    permitVolume: '~3,500 commercial permits/year',
    yoyGrowthPct: '9.1',
    notes: 'One of Houston metro\'s fastest-growing suburbs. Uses Brazoria County Fire Marshal for fire suppression review. Streamlined review for <5,000 SF tenant improvements.',
  },
  {
    metro: 'Houston Metro',
    city: 'Sugar Land',
    county: 'Fort Bend County',
    state: 'TX',
    ahjName: 'City of Sugar Land Building & Development Services',
    portalUrl: 'https://www.sugarlandtx.gov/275/Permits',
    phone: '(281) 275-2900',
    avgReviewDaysBuilding: 12,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 14,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['office', 'retail', 'medical']),
    permitVolume: '~4,000 commercial permits/year',
    yoyGrowthPct: '7.3',
    notes: 'Notably faster reviews than City of Houston. City has adopted ordinances beyond state minimum. Fort Bend County Health Dept coordinates on food service permits.',
  },
  {
    metro: 'Houston Metro',
    city: 'The Woodlands / Conroe',
    county: 'Montgomery County',
    state: 'TX',
    ahjName: 'Montgomery County Engineering Department',
    portalUrl: 'https://www.mctx.org/departments/engineer/permits',
    phone: '(936) 539-7801',
    avgReviewDaysBuilding: 20,
    avgReviewDaysElectrical: 10,
    avgReviewDaysPlumbing: 10,
    avgReviewDaysMechanical: 12,
    avgReviewDaysFire: null,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['office', 'healthcare', 'retail', 'hospitality']),
    permitVolume: '~6,000 commercial permits/year',
    yoyGrowthPct: '10.4',
    notes: 'The Woodlands is a master-planned community with additional HOA/design review. Conroe has its own permit office. Fastest-growing sub-market in Houston metro by permit volume.',
  },

  // ─────────────────────────────────────────────
  // AUSTIN METRO, TX — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Austin Metro',
    city: 'Austin',
    county: 'Travis County',
    state: 'TX',
    ahjName: 'Austin Development Services Department (DSD)',
    portalUrl: 'https://austinbuildandconnect.austintexas.gov',
    feeScheduleUrl: 'https://www.austintexas.gov/sites/default/files/files/Development_Services/DSD-Building-Fee-Schedule.pdf',
    phone: '(512) 978-4000',
    address: '6310 Wilhelmina Delco Dr, Austin, TX 78752',
    avgReviewDaysBuilding: 28,
    avgReviewDaysElectrical: 10,
    avgReviewDaysPlumbing: 10,
    avgReviewDaysMechanical: 14,
    avgReviewDaysFire: 21,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'multifamily', 'tech-campus', 'retail', 'healthcare']),
    permitVolume: '~40,000 commercial permits/year',
    yoyGrowthPct: '12.1',
    notes: 'Submit via Austin Build + Connect portal. Impervious cover calculation required for most commercial projects. Heritage tree survey may be required. Austin Energy Green Building review for energy-intensive uses. Austin Water Utility review for large developments. Expect 30–90 days for major commercial; has express review program for smaller projects.',
  },
  {
    metro: 'Austin Metro',
    city: 'Round Rock',
    county: 'Williamson County',
    state: 'TX',
    ahjName: 'City of Round Rock Development Services',
    portalUrl: 'https://www.roundrocktexas.gov/departments/development-services/permits/',
    phone: '(512) 218-5428',
    avgReviewDaysBuilding: 14,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 14,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['retail', 'industrial', 'office', 'multifamily']),
    permitVolume: '~5,000 commercial permits/year',
    yoyGrowthPct: '11.2',
    notes: 'Significantly faster than City of Austin. Large tech and manufacturing presence (Dell, IKEA). Uses CSS (Construction Services System) for permitting. Streamlined for commercial tenant improvements.',
  },
  {
    metro: 'Austin Metro',
    city: 'Cedar Park',
    county: 'Williamson County',
    state: 'TX',
    ahjName: 'City of Cedar Park Planning & Development Services',
    portalUrl: 'https://www.cedarparktexas.gov/government/departments/planning/permits',
    phone: '(512) 401-5050',
    avgReviewDaysBuilding: 12,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 8,
    avgReviewDaysFire: 12,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['retail', 'multifamily', 'office']),
    permitVolume: '~3,000 commercial permits/year',
    yoyGrowthPct: '13.5',
    notes: 'One of fastest-growing Austin suburbs. Extremely fast reviews for standard commercial projects. City proactively works with developers to expedite reviews.',
  },
  {
    metro: 'Austin Metro',
    city: 'Georgetown',
    county: 'Williamson County',
    state: 'TX',
    ahjName: 'City of Georgetown Inspections Division',
    portalUrl: 'https://georgetown.org/departments/community-development/building-inspections/',
    phone: '(512) 930-3748',
    avgReviewDaysBuilding: 15,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 15,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['retail', 'industrial', 'multifamily']),
    permitVolume: '~2,500 commercial permits/year',
    yoyGrowthPct: '14.8',
    notes: 'Fastest-growing city in the US (per Census 2023). Samsung announced major fab plant nearby. Historic Downtown Overlay District requires additional design review for projects in historic core.',
  },

  // ─────────────────────────────────────────────
  // MIAMI METRO, FL — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Miami Metro',
    city: 'Miami',
    county: 'Miami-Dade County',
    state: 'FL',
    ahjName: 'City of Miami Building Department',
    portalUrl: 'https://www.miamigov.com/Build-Miami',
    feeScheduleUrl: 'https://www.miamigov.com/files/sharedassets/public/v/3/departments/building/fee-schedule.pdf',
    phone: '(305) 416-1100',
    address: '444 SW 2nd Ave, Miami, FL 33130',
    avgReviewDaysBuilding: 20,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 21,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['multifamily', 'hospitality', 'retail', 'office', 'mixed-use']),
    permitVolume: '~25,000 commercial permits/year',
    yoyGrowthPct: '15.3',
    notes: 'Use iBuild Miami portal. Miami-Dade County wind speed requirements (High-Velocity Hurricane Zone — HVHZ) mandate enhanced structural standards. Florida Building Code 8th Edition required. Miami 21 zoning code governs land use. Fire Marshal review through Miami-Dade County Fire Rescue.',
  },
  {
    metro: 'Miami Metro',
    city: 'Miami-Dade (unincorporated)',
    county: 'Miami-Dade County',
    state: 'FL',
    ahjName: 'Miami-Dade County Regulatory & Economic Resources (RER)',
    portalUrl: 'https://www.miamidade.gov/permits',
    phone: '(786) 315-2880',
    address: '11805 SW 26th St, Miami, FL 33175',
    avgReviewDaysBuilding: 25,
    avgReviewDaysElectrical: 10,
    avgReviewDaysPlumbing: 10,
    avgReviewDaysMechanical: 12,
    avgReviewDaysFire: 25,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['industrial', 'logistics', 'retail', 'healthcare']),
    permitVolume: '~18,000 commercial permits/year',
    yoyGrowthPct: '11.7',
    notes: 'Covers unincorporated county areas. HVHZ wind requirements apply countywide. Environmental Resource Management (DERM) review for sites near wetlands/waterways. Miami-Dade Water and Sewer coordination required for most projects.',
  },
  {
    metro: 'Miami Metro',
    city: 'Fort Lauderdale',
    county: 'Broward County',
    state: 'FL',
    ahjName: 'City of Fort Lauderdale Development Services',
    portalUrl: 'https://www.fortlauderdale.gov/departments/sustainable-development/development-services',
    phone: '(954) 828-5955',
    avgReviewDaysBuilding: 18,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 18,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'multifamily', 'hospitality', 'marine-commercial']),
    permitVolume: '~12,000 commercial permits/year',
    yoyGrowthPct: '13.2',
    notes: 'Broward County HVHZ requirements apply. Marine/waterfront projects require South Florida Water Management District (SFWMD) permits. Uses eLAS (Electronic Land Administration System). Strong downtown development pipeline.',
  },
  {
    metro: 'Miami Metro',
    city: 'Coral Gables',
    county: 'Miami-Dade County',
    state: 'FL',
    ahjName: 'City of Coral Gables Building Division',
    portalUrl: 'https://www.coralgables.com/departments/planning-zoning/building-division',
    phone: '(305) 460-5228',
    avgReviewDaysBuilding: 30,
    avgReviewDaysElectrical: 10,
    avgReviewDaysPlumbing: 10,
    avgReviewDaysMechanical: 14,
    avgReviewDaysFire: 25,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['office', 'retail', 'hospitality', 'multifamily']),
    permitVolume: '~4,000 commercial permits/year',
    yoyGrowthPct: '7.4',
    notes: 'Very strict design review — Mediterranean Revival architectural standards enforced. Board of Architects review required for most commercial projects. Longer review times due to design compliance standards. High-prestige office and retail market.',
  },
  {
    metro: 'Miami Metro',
    city: 'Doral',
    county: 'Miami-Dade County',
    state: 'FL',
    ahjName: 'City of Doral Building & Zoning Division',
    portalUrl: 'https://www.cityofdoral.com/building-zoning/',
    phone: '(305) 593-6630',
    avgReviewDaysBuilding: 15,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 15,
    marketTier: 2,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['industrial', 'logistics', 'office', 'retail']),
    permitVolume: '~5,000 commercial permits/year',
    yoyGrowthPct: '16.8',
    notes: 'Miami\'s logistics and international trade hub (near Miami International Airport). Fastest-growing city in Florida by permit count. Strong demand from Latin American companies establishing US operations. Streamlined reviews for industrial and office.',
  },

  // ─────────────────────────────────────────────
  // NASHVILLE METRO, TN — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Nashville Metro',
    city: 'Nashville',
    county: 'Davidson County',
    state: 'TN',
    ahjName: 'Metro Nashville Codes Administration',
    portalUrl: 'https://aes.nashville.gov',
    feeScheduleUrl: 'https://www.nashville.gov/departments/codes/permits-applications/fee-schedule',
    phone: '(615) 862-6500',
    address: '800 2nd Ave S, Nashville, TN 37210',
    avgReviewDaysBuilding: 15,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 18,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'multifamily', 'hospitality', 'healthcare', 'entertainment']),
    permitVolume: '~30,000 commercial permits/year',
    yoyGrowthPct: '11.8',
    notes: 'Submit via AES (Accela Engagement Suite). Metro Nashville / Davidson County is consolidated city-county government. Nashville Fire Department reviews all fire protection systems. Strong Downtown Core and Germantown development corridors. Oracle, Amazon, and AllianceBernstein HQ relocations driving office demand.',
  },
  {
    metro: 'Nashville Metro',
    city: 'Franklin',
    county: 'Williamson County',
    state: 'TN',
    ahjName: 'City of Franklin Building & Neighborhood Services',
    portalUrl: 'https://www.franklintn.gov/government/departments/building-neighborhood-services',
    phone: '(615) 791-3212',
    avgReviewDaysBuilding: 12,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 12,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'retail', 'healthcare', 'multifamily']),
    permitVolume: '~8,000 commercial permits/year',
    yoyGrowthPct: '14.2',
    notes: 'One of the hottest suburban commercial markets in the Southeast. Cool Springs submarket is major corporate campus destination. Historic Downtown Franklin has overlay design requirements. Williamson County has among highest median household incomes in US, driving premium retail and medical.',
  },
  {
    metro: 'Nashville Metro',
    city: 'Brentwood',
    county: 'Williamson County',
    state: 'TN',
    ahjName: 'City of Brentwood Building & Codes',
    portalUrl: 'https://www.brentwoodtn.gov/government/departments/community-development/building-codes',
    phone: '(615) 371-0060',
    avgReviewDaysBuilding: 10,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 10,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['office', 'medical', 'retail']),
    permitVolume: '~3,500 commercial permits/year',
    yoyGrowthPct: '8.9',
    notes: 'Small but very high-value commercial market. Several Fortune 500 HQ locations. Known for fast, collaborative review process. Strict tree preservation and landscaping requirements.',
  },
  {
    metro: 'Nashville Metro',
    city: 'Murfreesboro',
    county: 'Rutherford County',
    state: 'TN',
    ahjName: 'City of Murfreesboro Building & Codes',
    portalUrl: 'https://www.murfreesborotn.gov/242/Building-Codes',
    phone: '(615) 893-5210',
    avgReviewDaysBuilding: 14,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 14,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['industrial', 'retail', 'multifamily', 'healthcare']),
    permitVolume: '~6,000 commercial permits/year',
    yoyGrowthPct: '12.6',
    notes: 'Among fastest-growing mid-sized cities in US. Large industrial and distribution presence along I-24 corridor. MTSU (Middle Tennessee State University) drives student housing and retail. Rutherford County has separate permit office for unincorporated areas.',
  },

  // ─────────────────────────────────────────────
  // DALLAS-FORT WORTH METRO, TX — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Dallas–Fort Worth Metro',
    city: 'Dallas',
    county: 'Dallas County',
    state: 'TX',
    ahjName: 'Dallas Development Services Department',
    portalUrl: 'https://developmentservicescenter.dallascityhall.com',
    feeScheduleUrl: 'https://dallascityhall.com/departments/sustainabledevelopment/development-services/Pages/permit-applications-and-fees.aspx',
    phone: '(214) 948-4480',
    address: '1500 Marilla St, Dallas, TX 75201',
    avgReviewDaysBuilding: 18,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 20,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'multifamily', 'retail', 'healthcare', 'industrial']),
    permitVolume: '~50,000 commercial permits/year',
    yoyGrowthPct: '9.4',
    notes: 'Online permit portal via Accela. TAS (Texas Accessibility Standards) review required for commercial. Dallas Fire-Rescue reviews fire protection systems. Uptown, Deep Ellum, and Design District corridors have active development. TxDOT coordination required for projects impacting state highway ROW.',
  },
  {
    metro: 'Dallas–Fort Worth Metro',
    city: 'Fort Worth',
    county: 'Tarrant County',
    state: 'TX',
    ahjName: 'City of Fort Worth Development Services',
    portalUrl: 'https://www.fortworthtexas.gov/departments/development-services',
    phone: '(817) 392-2222',
    avgReviewDaysBuilding: 15,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 17,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['industrial', 'logistics', 'office', 'healthcare', 'aviation']),
    permitVolume: '~20,000 commercial permits/year',
    yoyGrowthPct: '10.2',
    notes: 'Strong industrial and aerospace presence (DFW Airport, Alliance Airport). Panther City growing as mixed-use destination. Fort Worth ISD construction driving education sector permits. Tarrant County has separate permit office for unincorporated areas.',
  },
  {
    metro: 'Dallas–Fort Worth Metro',
    city: 'Frisco',
    county: 'Collin County',
    state: 'TX',
    ahjName: 'City of Frisco Building Inspections',
    portalUrl: 'https://www.friscotexas.gov/1046/Building-Inspections',
    phone: '(972) 292-5370',
    avgReviewDaysBuilding: 10,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 12,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'retail', 'healthcare', 'sports-entertainment', 'multifamily']),
    permitVolume: '~12,000 commercial permits/year',
    yoyGrowthPct: '18.5',
    notes: 'Fastest-growing large city in Texas. Dallas Cowboys (Star) and FC Dallas campus driving mixed-use development. PGA of America HQ relocated to Frisco. Excellent permit response times — city invests heavily in review staff. Legacy West and Hall Park are major corporate campus destinations.',
  },
  {
    metro: 'Dallas–Fort Worth Metro',
    city: 'Plano',
    county: 'Collin County',
    state: 'TX',
    ahjName: 'City of Plano Building Inspections',
    portalUrl: 'https://www.plano.gov/315/Building-Inspection',
    phone: '(972) 941-7151',
    avgReviewDaysBuilding: 12,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 14,
    marketTier: 1,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['office', 'tech-campus', 'retail', 'healthcare']),
    permitVolume: '~10,000 commercial permits/year',
    yoyGrowthPct: '7.8',
    notes: 'Mature corporate campus market — Toyota, Toyota Financial, JPMorgan, Capital One. Legacy business park is one of DFW\'s largest office nodes. Established infrastructure means faster utility coordination than newer suburbs.',
  },
  {
    metro: 'Dallas–Fort Worth Metro',
    city: 'McKinney',
    county: 'Collin County',
    state: 'TX',
    ahjName: 'City of McKinney Development Services',
    portalUrl: 'https://www.mckinneytexas.org/2092/Building-Permits',
    phone: '(972) 547-7400',
    avgReviewDaysBuilding: 12,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 14,
    marketTier: 2,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['industrial', 'office', 'multifamily', 'retail']),
    permitVolume: '~7,000 commercial permits/year',
    yoyGrowthPct: '16.3',
    notes: 'Historic downtown overlay district for projects in historic core. McKinney National Airport driving aviation-adjacent industrial development. Strong medical corridor along US-75.',
  },

  // ─────────────────────────────────────────────
  // CHARLOTTE METRO, NC — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Charlotte Metro',
    city: 'Charlotte',
    county: 'Mecklenburg County',
    state: 'NC',
    ahjName: 'Mecklenburg County Land Use & Environmental Services Agency (LUESA)',
    portalUrl: 'https://luesa.mecklenburgcountync.gov/building-development-commission',
    feeScheduleUrl: 'https://luesa.mecklenburgcountync.gov/building-development-commission/permit-fees',
    phone: '(980) 314-2633',
    address: '2145 Suttle Ave, Charlotte, NC 28208',
    avgReviewDaysBuilding: 15,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 15,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'financial-services', 'multifamily', 'industrial', 'healthcare']),
    permitVolume: '~35,000 commercial permits/year',
    yoyGrowthPct: '13.6',
    notes: 'Single AHJ for Charlotte and Mecklenburg County (consolidated). Major banking HQ presence — Bank of America, Truist, LendingTree, Honeywell. Uptown Charlotte and South End corridors are primary commercial development zones. NC Fire Prevention Code requires fire marshal review for suppression systems.',
  },
  {
    metro: 'Charlotte Metro',
    city: 'Huntersville',
    county: 'Mecklenburg County',
    state: 'NC',
    ahjName: 'Town of Huntersville Planning Department',
    portalUrl: 'https://www.huntersville.org/228/Permits-Inspections',
    phone: '(704) 766-2220',
    avgReviewDaysBuilding: 10,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 12,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['retail', 'multifamily', 'office', 'industrial']),
    permitVolume: '~3,000 commercial permits/year',
    yoyGrowthPct: '11.4',
    notes: 'Lake Norman area driving hospitality and premium retail development. Close proximity to Charlotte Douglas Airport expansion. Fast-track review available for projects under $500K.',
  },
  {
    metro: 'Charlotte Metro',
    city: 'Gastonia',
    county: 'Gaston County',
    state: 'NC',
    ahjName: 'City of Gastonia Inspections Division',
    portalUrl: 'https://www.cityofgastonia.com/index.aspx?NID=187',
    phone: '(704) 866-6773',
    avgReviewDaysBuilding: 12,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 12,
    marketTier: 2,
    constructionActivity: 'moderate',
    primarySectors: JSON.stringify(['industrial', 'retail', 'healthcare']),
    permitVolume: '~4,000 commercial permits/year',
    yoyGrowthPct: '6.2',
    notes: 'Lower cost industrial market west of Charlotte. I-85 corridor driving logistics/distribution growth. Gaston County has separate permit office for unincorporated areas. Manufacturing revival in textile-to-logistics conversion.',
  },

  // ─────────────────────────────────────────────
  // PHOENIX METRO, AZ — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Phoenix Metro',
    city: 'Phoenix',
    county: 'Maricopa County',
    state: 'AZ',
    ahjName: 'City of Phoenix Planning & Development Department',
    portalUrl: 'https://www.phoenix.gov/pdd/services',
    feeScheduleUrl: 'https://www.phoenix.gov/pdd/pdfs/fees.pdf',
    phone: '(602) 262-7811',
    address: '200 W Washington St, Phoenix, AZ 85003',
    avgReviewDaysBuilding: 12,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 14,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['industrial', 'semiconductor', 'office', 'multifamily', 'retail']),
    permitVolume: '~55,000 commercial permits/year',
    yoyGrowthPct: '14.7',
    notes: 'Use Enhanced Permit Portal (EPP) for online submissions. Arizona is a right-to-work state with generally streamlined permitting. TSMC and Intel fabs driving massive industrial permit volume in West Valley. Phoenix is now top 5 US market by commercial permit volume. Desert monsoon season affects inspection scheduling Jun–Sep.',
  },
  {
    metro: 'Phoenix Metro',
    city: 'Scottsdale',
    county: 'Maricopa County',
    state: 'AZ',
    ahjName: 'City of Scottsdale Community Development',
    portalUrl: 'https://www.scottsdaleaz.gov/permits',
    phone: '(480) 312-2500',
    avgReviewDaysBuilding: 14,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 14,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['hospitality', 'office', 'medical', 'retail', 'luxury-multifamily']),
    permitVolume: '~15,000 commercial permits/year',
    yoyGrowthPct: '10.3',
    notes: 'SkySong Innovation Center and financial services corridor driving office demand. McDowell Road Arts District has design overlay requirements. Strong hospitality and resort development pipeline. Review times slightly longer than Phoenix due to more rigorous design standards.',
  },
  {
    metro: 'Phoenix Metro',
    city: 'Mesa',
    county: 'Maricopa County',
    state: 'AZ',
    ahjName: 'City of Mesa Development Services',
    portalUrl: 'https://www.mesaaz.gov/business/building-safety',
    phone: '(480) 644-2262',
    avgReviewDaysBuilding: 10,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 12,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['industrial', 'aerospace', 'retail', 'healthcare', 'multifamily']),
    permitVolume: '~18,000 commercial permits/year',
    yoyGrowthPct: '12.9',
    notes: 'Phoenix-Mesa Gateway Airport fueling aerospace manufacturing expansion. Apple, Meta, and Google data centers driving industrial/critical infrastructure permits. Mesa has one of AZ\'s most efficient permit review processes. Chicago Cubs spring training complex driving hospitality.',
  },
  {
    metro: 'Phoenix Metro',
    city: 'Chandler',
    county: 'Maricopa County',
    state: 'AZ',
    ahjName: 'City of Chandler Development Services',
    portalUrl: 'https://www.chandleraz.gov/government/departments/development-services/building-safety',
    phone: '(480) 782-3200',
    avgReviewDaysBuilding: 10,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 12,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['semiconductor', 'industrial', 'office', 'retail']),
    permitVolume: '~10,000 commercial permits/year',
    yoyGrowthPct: '15.6',
    notes: 'Intel\'s Chandler campus is world\'s largest semiconductor manufacturing site — driving enormous industrial permit activity. Silicon Desert designation. Chandler Fashion Center area driving retail. Very fast review process for experienced applicants — online pre-application available.',
  },

  // ─────────────────────────────────────────────
  // DENVER METRO, CO — Tier 2 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Denver Metro',
    city: 'Denver',
    county: 'Denver County',
    state: 'CO',
    ahjName: 'Denver Community Planning and Development (CPD)',
    portalUrl: 'https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Community-Planning-and-Development/Building-Permits-Inspections',
    feeScheduleUrl: 'https://www.denvergov.org/content/dam/denvergov/Portals/646/documents/Permit-Fee-Schedule.pdf',
    phone: '(720) 865-2750',
    address: '201 W Colfax Ave, Denver, CO 80202',
    avgReviewDaysBuilding: 20,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 12,
    avgReviewDaysFire: 21,
    marketTier: 1,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['office', 'multifamily', 'tech', 'healthcare', 'cannabis-retail']),
    permitVolume: '~28,000 commercial permits/year',
    yoyGrowthPct: '6.8',
    notes: 'Submit via Denver\'s online eDPS portal. Denver is city and county consolidated government. Colorado Energy Code (IECC 2021) with state amendments required. Cannabis retail permits are unique to Colorado — separate licensing. Union Station and RiNo Art District driving mixed-use. Fire protection reviewed by Denver Fire Department.',
  },
  {
    metro: 'Denver Metro',
    city: 'Aurora',
    county: 'Arapahoe County',
    state: 'CO',
    ahjName: 'City of Aurora Building Division',
    portalUrl: 'https://www.auroragov.org/business_in_aurora/permits_licenses_and_inspections',
    phone: '(303) 739-7420',
    avgReviewDaysBuilding: 15,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 15,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['healthcare', 'industrial', 'retail', 'multifamily']),
    permitVolume: '~8,000 commercial permits/year',
    yoyGrowthPct: '7.9',
    notes: 'Fitzsimons Life Science Campus driving significant healthcare and biotech construction. Denver International Airport proximity driving logistics/industrial along E-470. Mixed jurisdiction — portions are in Arapahoe, Adams, and Douglas Counties.',
  },
  {
    metro: 'Denver Metro',
    city: 'Lakewood',
    county: 'Jefferson County',
    state: 'CO',
    ahjName: 'City of Lakewood Building & Safety',
    portalUrl: 'https://www.lakewood.org/Government/Departments/Community-Resources/Building-and-Safety',
    phone: '(303) 987-7500',
    avgReviewDaysBuilding: 14,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 14,
    marketTier: 2,
    constructionActivity: 'moderate',
    primarySectors: JSON.stringify(['retail', 'office', 'healthcare', 'industrial']),
    permitVolume: '~5,000 commercial permits/year',
    yoyGrowthPct: '5.3',
    notes: 'Belmar development district is a model urban mixed-use redevelopment. Colorado Mills Mall area strong retail corridor. Federal Center presence (multiple federal agencies) drives some commercial services construction. Jefferson County handles unincorporated areas separately.',
  },

  // ─────────────────────────────────────────────
  // ATLANTA METRO, GA — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Atlanta Metro',
    city: 'Atlanta',
    county: 'Fulton County',
    state: 'GA',
    ahjName: 'City of Atlanta Department of City Planning',
    portalUrl: 'https://atlantaga.viewpointcloud.com',
    phone: '(404) 330-6145',
    address: '55 Trinity Ave SW, Atlanta, GA 30303',
    avgReviewDaysBuilding: 20,
    avgReviewDaysElectrical: 10,
    avgReviewDaysPlumbing: 10,
    avgReviewDaysMechanical: 14,
    avgReviewDaysFire: 21,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'film-studio', 'multifamily', 'logistics', 'healthcare']),
    permitVolume: '~20,000 commercial permits/year',
    yoyGrowthPct: '11.2',
    notes: 'Submit via ViewPoint Cloud portal. Georgia Film Commission has made Atlanta major film production hub — studio construction is booming. Beltline project creating massive mixed-use development corridor. Atlanta Fire Rescue reviews fire systems. Fulton County handles unincorporated areas separately. Opportunity Zones cover large portions of south and west Atlanta.',
  },
  {
    metro: 'Atlanta Metro',
    city: 'Gwinnett County',
    county: 'Gwinnett County',
    state: 'GA',
    ahjName: 'Gwinnett County Planning & Development Division',
    portalUrl: 'https://www.gwinnettcounty.com/portal/gwinnett/Departments/PlanningAndDevelopment',
    phone: '(678) 518-6000',
    avgReviewDaysBuilding: 15,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 15,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['industrial', 'logistics', 'retail', 'multifamily', 'healthcare']),
    permitVolume: '~15,000 commercial permits/year',
    yoyGrowthPct: '13.1',
    notes: 'Largest county in metro Atlanta by development activity. I-85 Northeast Corridor is major logistics/distribution hub. Sugarloaf area driving premium retail and office. Strong multifamily pipeline driven by tech worker influx. Gwinnett County Fire & Emergency Services handles fire permits.',
  },
  {
    metro: 'Atlanta Metro',
    city: 'Sandy Springs',
    county: 'Fulton County',
    state: 'GA',
    ahjName: 'City of Sandy Springs Community Development',
    portalUrl: 'https://www.sandyspringsga.gov/government/departments/community-development/building-permits',
    phone: '(770) 730-5600',
    avgReviewDaysBuilding: 14,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 14,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['office', 'healthcare', 'retail', 'multifamily']),
    permitVolume: '~4,500 commercial permits/year',
    yoyGrowthPct: '8.6',
    notes: 'Premium north Atlanta office market — UPS, Cox Enterprises, Newell Brands HQ. City Springs mixed-use development reshaping downtown core. Perimeter Center submarket is major retail and office hub. Incorporated in 2005 — relatively streamlined modern permit process.',
  },
  {
    metro: 'Atlanta Metro',
    city: 'Marietta / Cobb County',
    county: 'Cobb County',
    state: 'GA',
    ahjName: 'Cobb County Community Development Agency',
    portalUrl: 'https://www.cobbcounty.org/community-development',
    phone: '(770) 528-2040',
    avgReviewDaysBuilding: 16,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 16,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['healthcare', 'industrial', 'office', 'retail']),
    permitVolume: '~10,000 commercial permits/year',
    yoyGrowthPct: '9.3',
    notes: 'Lockheed Martin Aeronautics presence drives aerospace/defense-adjacent industrial. Cumberland/Galleria area is major mixed-use destination. Truist Park (Atlanta Braves) and The Battery driving entertainment and hospitality construction. Wellstar Health System building throughout county.',
  },

  // ─────────────────────────────────────────────
  // RALEIGH-DURHAM, NC — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Raleigh–Durham Metro',
    city: 'Raleigh',
    county: 'Wake County',
    state: 'NC',
    ahjName: 'City of Raleigh Inspections & Permits',
    portalUrl: 'https://raleighnc.gov/permits',
    feeScheduleUrl: 'https://raleighnc.gov/permits/fees',
    phone: '(919) 996-2500',
    address: '1 Exchange Plaza Suite 400, Raleigh, NC 27601',
    avgReviewDaysBuilding: 12,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 14,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'tech-campus', 'life-sciences', 'multifamily', 'healthcare']),
    permitVolume: '~22,000 commercial permits/year',
    yoyGrowthPct: '16.2',
    notes: 'Use ProjectDox for plan review. Research Triangle Park (RTP) driving massive life sciences and tech construction. Apple, Google, and Amazon announced major Raleigh investments. NC State\'s Centennial Campus creating innovation corridor. Fast-growing market with competitive permit office — online express review for projects under $50K. Wake County has separate office for unincorporated areas.',
  },
  {
    metro: 'Raleigh–Durham Metro',
    city: 'Durham',
    county: 'Durham County',
    state: 'NC',
    ahjName: 'City of Durham Inspections Department',
    portalUrl: 'https://durhamnc.gov/278/Inspections',
    phone: '(919) 560-4144',
    avgReviewDaysBuilding: 14,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 15,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['life-sciences', 'healthcare', 'multifamily', 'office', 'tech']),
    permitVolume: '~10,000 commercial permits/year',
    yoyGrowthPct: '18.4',
    notes: 'Duke University Health System and NC Central University drive healthcare and education construction. Durham Innovation District reshaping downtown. Strong biotech pipeline in Research Triangle Park (Durham side). American Tobacco Campus anchors historic renovation market. Fastest-growing permit market in the Triangle.',
  },
  {
    metro: 'Raleigh–Durham Metro',
    city: 'Cary',
    county: 'Wake County',
    state: 'NC',
    ahjName: 'Town of Cary Inspections & Permits',
    portalUrl: 'https://www.townofcary.org/departments-divisions-a-z/inspections-permits',
    phone: '(919) 469-4050',
    avgReviewDaysBuilding: 10,
    avgReviewDaysElectrical: 5,
    avgReviewDaysPlumbing: 5,
    avgReviewDaysMechanical: 7,
    avgReviewDaysFire: 12,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['office', 'retail', 'healthcare', 'tech-campus']),
    permitVolume: '~8,000 commercial permits/year',
    yoyGrowthPct: '12.7',
    notes: 'SAS Institute HQ anchors technology corridor. Regency Centers (Waverly Place) and Fenton mixed-use driving retail. Known nationally for excellent city services and efficient permitting. One of the best cities for business in NC. 10 Percent Innovation District under development.',
  },

  // ─────────────────────────────────────────────
  // SAN ANTONIO, TX — Tier 2 Market
  // ─────────────────────────────────────────────
  {
    metro: 'San Antonio Metro',
    city: 'San Antonio',
    county: 'Bexar County',
    state: 'TX',
    ahjName: 'City of San Antonio Development Services Department',
    portalUrl: 'https://saenterprise.sanantonio.gov',
    feeScheduleUrl: 'https://www.sanantonio.gov/DSD/Applications-Forms/Fee-Schedules',
    phone: '(210) 207-1111',
    address: '1901 S Alamo St, San Antonio, TX 78204',
    avgReviewDaysBuilding: 16,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 18,
    marketTier: 2,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['healthcare', 'military-support', 'retail', 'multifamily', 'hospitality']),
    permitVolume: '~18,000 commercial permits/year',
    yoyGrowthPct: '8.1',
    notes: 'Submit via SAEnterprise portal. TAS (Texas Accessibility Standards) review required. San Antonio Fire Department reviews fire systems. Strong military presence (Fort Sam Houston, Lackland, Randolph) drives healthcare and support services. Tourism/River Walk drives hospitality construction. Toyota manufacturing plant drives auto-adjacent industrial.',
  },
  {
    metro: 'San Antonio Metro',
    city: 'New Braunfels',
    county: 'Comal County',
    state: 'TX',
    ahjName: 'City of New Braunfels Building Division',
    portalUrl: 'https://www.nbtexas.org/1060/Building-Division',
    phone: '(830) 221-4055',
    avgReviewDaysBuilding: 14,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 14,
    marketTier: 2,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['industrial', 'retail', 'multifamily', 'hospitality']),
    permitVolume: '~3,500 commercial permits/year',
    yoyGrowthPct: '21.4',
    notes: 'Fastest-growing city in US 2023 (Census Bureau). Located between San Antonio and Austin on I-35 — benefits from both metros. Amazon, H-E-B distribution. Strong tourism (Schlitterbahn) drives hospitality. Comal County handles unincorporated areas.',
  },

  // ─────────────────────────────────────────────
  // TAMPA-ST. PETE METRO, FL — Tier 1 Market
  // ─────────────────────────────────────────────
  {
    metro: 'Tampa–St. Petersburg Metro',
    city: 'Tampa',
    county: 'Hillsborough County',
    state: 'FL',
    ahjName: 'City of Tampa Construction Services',
    portalUrl: 'https://www.tampagov.net/construction-services',
    phone: '(813) 274-3100',
    address: '1400 N Blvd, Tampa, FL 33607',
    avgReviewDaysBuilding: 14,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 15,
    marketTier: 1,
    constructionActivity: 'very-high',
    primarySectors: JSON.stringify(['office', 'multifamily', 'healthcare', 'logistics', 'hospitality']),
    permitVolume: '~25,000 commercial permits/year',
    yoyGrowthPct: '14.1',
    notes: 'Florida Building Code + HVHZ wind requirements in coastal areas. Tampa Innovation Partnership driving life sciences. Water Street Tampa is $3B mixed-use district under development. Tampa Port redevelopment creating industrial/maritime demand. Significant post-hurricane Helene/Milton rebuild activity. FEMA floodplain maps require elevation certificates for most commercial near waterfront.',
  },
  {
    metro: 'Tampa–St. Petersburg Metro',
    city: 'St. Petersburg',
    county: 'Pinellas County',
    state: 'FL',
    ahjName: 'City of St. Petersburg Building Services',
    portalUrl: 'https://www.stpete.org/permits',
    phone: '(727) 893-7231',
    avgReviewDaysBuilding: 14,
    avgReviewDaysElectrical: 7,
    avgReviewDaysPlumbing: 7,
    avgReviewDaysMechanical: 10,
    avgReviewDaysFire: 15,
    marketTier: 1,
    constructionActivity: 'high',
    primarySectors: JSON.stringify(['arts', 'hospitality', 'office', 'multifamily', 'healthcare']),
    permitVolume: '~10,000 commercial permits/year',
    yoyGrowthPct: '11.3',
    notes: 'Downtown St. Pete arts and innovation district booming. Tropicana Field redevelopment (Historic Gas Plant District) is major mixed-use project. Florida HVHZ coastal requirements apply throughout. Pinellas County handles unincorporated areas. Strong waterfront hospitality pipeline.',
  },
];

async function seedMarkets() {
  console.log('🌱 Seeding market database...');
  console.log(`📍 Inserting ${markets.length} jurisdictions across ${new Set(markets.map(m => m.metro)).size} metros`);

  // Clear existing data before re-seeding (idempotent)
  await db.delete(schema.jurisdictions);
  console.log('  ✓ Cleared existing jurisdiction data');

  // Insert all markets
  let inserted = 0;
  for (const market of markets) {
    await db.insert(schema.jurisdictions).values(market);
    inserted++;
    process.stdout.write(`\r  ✓ ${inserted}/${markets.length}: ${market.city}, ${market.state}`);
  }

  console.log('\n');

  const metroGroups = markets.reduce((acc, m) => {
    acc[m.metro] = (acc[m.metro] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  console.log('📊 Market summary:');
  Object.entries(metroGroups).forEach(([metro, count]) => {
    console.log(`   ${metro}: ${count} AHJ${count > 1 ? 's' : ''}`);
  });

  console.log('\n✅ Market database seeded successfully.');
  await client.end();
}

seedMarkets().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
